question_data = [
    {"question": "Il Sole è una stella.", "answer": "Vero"},
    {"question": "L'Australia è un continente.", "answer": "Vero"},
    {"question": "Il numero atomico dell'oro è 79.", "answer": "Vero"},
    {"question": "La capitale della Francia è Lione.", "answer": "Falso"},
    {"question": "Gli squali sono mammiferi.", "answer": "Falso"},
    {"question": "Il Monte Everest è la montagna più alta del mondo.", "answer": "Vero"},
    {"question": "Il corpo umano ha 4 polmoni.", "answer": "Falso"},
    {"question": "L'acqua bolle a 100 gradi Celsius a livello del mare.", "answer": "Vero"},
    {"question": "Il Python è un linguaggio di programmazione.", "answer": "Vero"},
    {"question": "La Gioconda è stata dipinta da Michelangelo.", "answer": "Falso"},
    {"question": "Il Titanic è affondato nel 1912.", "answer": "Vero"},
    {"question": "La velocità della luce è maggiore della velocità del suono.", "answer": "Vero"},
    {"question": "Il Mar Morto è un oceano.", "answer": "Falso"},
    {"question": "Le fette biscottate hanno più calorie del pane fresco a parità di peso.", "answer": "Vero"},
    {"question": "L'unghia del pollice cresce più velocemente delle altre.", "answer": "Falso"},
    {"question": "Il DNA sta per Acido Desossiribonucleico.", "answer": "Vero"},
    {"question": "Roma è stata fondata nel 753 a.C.", "answer": "Vero"},
    {"question": "Il pipistrello è un uccello.", "answer": "Falso"},
    {"question": "Esistono 365 giorni in un anno bisestile.", "answer": "Falso"},
    {"question": "La Grande Muraglia Cinese è visibile dalla Luna a occhio nudo.", "answer": "Falso"},
    {"question": "Il Rio delle Amazzoni si trova in Sud America.", "answer": "Vero"},
    {"question": "L'inventore della lampadina è Thomas Edison.", "answer": "Vero"},
    {"question": "L'Islanda è coperta interamente di ghiaccio.", "answer": "Falso"},
    {"question": "Il simbolo chimico dell'argento è Ag.", "answer": "Vero"},
    {"question": "La Seconda Guerra Mondiale è finita nel 1945.", "answer": "Vero"},
    {"question": "I pinguini vivono al Polo Nord.", "answer": "Falso"},
    {"question": "Il cuore umano ha quattro camere.", "answer": "Vero"},
    {"question": "L'ottone è un elemento puro.", "answer": "Falso"},
    {"question": "La lingua italiana deriva dal latino.", "answer": "Vero"},
    {"question": "Un esagono ha sette lati.", "answer": "Falso"},
    {"question": "La luna emette luce propria.", "answer": "Falso"},
    {"question": "L'ozono protegge la Terra dai raggi UV.", "answer": "Vero"},
    {"question": "Alessandro Volta ha inventato la pila.", "answer": "Vero"},
    {"question": "Il Kilimangiaro è un vulcano.", "answer": "Vero"},
    {"question": "Le balene respirano attraverso le branchie.", "answer": "Falso"},
    {"question": "Il Giappone è un arcipelago.", "answer": "Vero"},
    {"question": "Venezia è costruita su 118 isole.", "answer": "Vero"},
    {"question": "L'indirizzo IP identifica un dispositivo in rete.", "answer": "Vero"},
    {"question": "Il rubino è tipicamente di colore blu.", "answer": "Falso"},
    {"question": "Dante Alighieri ha scritto la Divina Commedia.", "answer": "Vero"},
    {"question": "Il Sahara è il deserto più vasto del mondo.", "answer": "Falso"},
    {"question": "Il ragno ha sei zampe.", "answer": "Falso"},
    {"question": "L'Empire State Building si trova a Chicago.", "answer": "Falso"},
    {"question": "La fibra ottica trasmette dati tramite impulsi luminosi.", "answer": "Vero"},
    {"question": "Il pianeta Marte è noto come il Pianeta Rosso.", "answer": "Vero"},
    {"question": "Il primo uomo sulla luna fuilil Neil Armstrong.", "answer": "Vero"},
    {"question": "L'erba è verde grazie alla clorofilla.", "answer": "Vero"},
    {"question": "Il violino ha sei corde.", "answer": "Falso"},
    {"question": "La Statua della Libertà è stata un regalo della Francia.", "answer": "Vero"},
    {"question": "Le lumache sono rettili.", "answer": "Falso"}
]